---
project:
  type: website

website:
  title: "Kickstarting the EV Revolution"
  navbar:
    background: "#00000"
    left:
      - href: index.qmd
        text: Home
      - href: Overview.qmd
        text: Overview

  page-footer:
    right: "This page is built with <3 & [Quarto](https://quarto.org/)."
   

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
---
